package com.example.product.infrastructure.seed;

import com.example.product.infrastructure.persistence.entity.ProductAttributeJpaEntity;
import com.example.product.infrastructure.persistence.entity.ProductJpaEntity;
import com.example.product.infrastructure.persistence.entity.SeedMigrationJpaEntity;
import com.example.product.infrastructure.persistence.repository.ProductAttributeRepository;
import com.example.product.infrastructure.persistence.repository.SeedMigrationRepository;
import com.example.product.infrastructure.persistence.repository.SpringDataProductRepository;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.Resource;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import jakarta.persistence.EntityManager;

import java.io.InputStream;
import java.util.List;
import java.util.stream.Collectors;

@Slf4j
@Service
@RequiredArgsConstructor
public class ProductSeedService {

    private final SeedMigrationRepository seedMigrationRepository;
    private final SpringDataProductRepository productRepository;
    private final ProductAttributeRepository productAttributeRepository;
    private final ObjectMapper objectMapper;
    private final EntityManager entityManager;

    @Value("classpath:db/seed/products-seed.json")
    private Resource seedFile;

    private static final String MIGRATION_NAME = "seed_products_v1_2026";

    @Transactional
    public void seedIfNeeded() {
        if (seedMigrationRepository.existsById(MIGRATION_NAME)) {
            log.info("event=product_seed_skip reason=already_applied migration={}", MIGRATION_NAME);
            return;
        }

        log.info("event=product_seed_start migration={}", MIGRATION_NAME);
        int inserted = 0;
        int skipped = 0;

        try (InputStream is = seedFile.getInputStream()) {
            List<ProductSeedRecord> records = objectMapper.readValue(is, new TypeReference<List<ProductSeedRecord>>() {});

            for (ProductSeedRecord record : records) {
                if (productRepository.existsById(record.getId()) || productRepository.existsBySlug(record.getSlug())) {
                    skipped++;
                    continue;
                }

                ProductJpaEntity product = ProductJpaEntity.builder()
                        .id(record.getId())
                        .categoryId(record.getCategoryId())
                        .brandId(record.getBrandId())
                        .name(record.getName())
                        .slug(record.getSlug())
                        .discountPercent(record.getDiscountPercent())
                        .status(record.getStatus() != null ? record.getStatus().toLowerCase() : "available")
                        .basePrice(record.getBasePrice())
                        .description(record.getDescription())
                        .overview(record.getOverview())
                        .totalSold(record.getTotalSold() != null ? record.getTotalSold() : 0)
                        .build();

                // Because ID is generated by default, setting it might require merge instead of save, or we can just persist it
                // We use standard save() which works if ID is explicitly set and strategy is IDENTITY (though Hibernate might ignore it sometimes)
                // Wait, if it's IDENTITY, Hibernate ignores the id we set during save. We should use native SQL to insert it to preserve the exact ID.
                // Or we can use entityManager.merge(product) or persist. Actually, Spring Data JPA save() checks if it's new.
                // The safest way to preserve exact ID with IDENTITY is to use native SQL or just let Hibernate do its thing and then setval.
                // Wait, if we use save(), Hibernate ignores the ID and uses auto-increment.
                // So let's insert using native query to force the ID.
                
                entityManager.createNativeQuery(
                        "INSERT INTO product (id, category_id, brand_id, name, slug, discount_percent, status, base_price, description, overview, total_sold, average_rating, total_reviews, created_at, updated_at) " +
                        "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)")
                        .setParameter(1, product.getId())
                        .setParameter(2, product.getCategoryId())
                        .setParameter(3, product.getBrandId())
                        .setParameter(4, product.getName())
                        .setParameter(5, product.getSlug())
                        .setParameter(6, product.getDiscountPercent())
                        .setParameter(7, product.getStatus())
                        .setParameter(8, product.getBasePrice())
                        .setParameter(9, product.getDescription())
                        .setParameter(10, product.getOverview())
                        .setParameter(11, product.getTotalSold())
                        .setParameter(12, product.getAverageRating())
                        .setParameter(13, product.getTotalReviews())
                        .executeUpdate();

                if (record.getSpecs() != null) {
                    for (ProductSeedRecord.Spec spec : record.getSpecs()) {
                        String valueStr = spec.getValue() != null ? String.join(", ", spec.getValue()) : "";
                        entityManager.createNativeQuery(
                            "INSERT INTO product_attribute (product_id, name, value) VALUES (?, ?, ?)")
                            .setParameter(1, product.getId())
                            .setParameter(2, spec.getName())
                            .setParameter(3, valueStr)
                            .executeUpdate();
                    }
                }

                inserted++;
            }

            // setval
            entityManager.createNativeQuery("SELECT setval('product_id_seq', (SELECT MAX(id) FROM product))")
                         .getSingleResult();

            SeedMigrationJpaEntity migration = new SeedMigrationJpaEntity();
            migration.setMigrationName(MIGRATION_NAME);
            seedMigrationRepository.save(migration);

            log.info("event=product_seed_complete migration={} inserted={} skipped={}", MIGRATION_NAME, inserted, skipped);

        } catch (Exception e) {
            log.error("event=product_seed_error migration={} message={}", MIGRATION_NAME, e.getMessage(), e);
            throw new RuntimeException("Product seed failed", e);
        }
    }
}
