CREATE TABLE "category" (
  "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "Name" varchar(100) NOT NULL,
  "Slug" varchar(120) NOT NULL,
  "IconPath" varchar(255) NOT NULL DEFAULT '...',
  "ImageUrl" varchar(500),
  "ParentId" BIGINT,
  "Description" text,
  "CreatedAt" timestamp NOT NULL DEFAULT now(),
  "UpdatedAt" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("Id")
);
ALTER TABLE "category" ADD CONSTRAINT "fk_category_parent" FOREIGN KEY ("ParentId") REFERENCES "category" ("Id") ON DELETE RESTRICT;
CREATE UNIQUE INDEX "idx_category_slug" ON "category" ("Slug");
CREATE INDEX "idx_category_parent_id" ON "category" ("ParentId");

CREATE TABLE "brand" (
  "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "Name" varchar(100) NOT NULL,
  "Slug" varchar(120) NOT NULL,
  "Country" varchar(50),
  "LogoPath" varchar(255),
  "CreatedAt" timestamp NOT NULL DEFAULT now(),
  "UpdatedAt" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX "idx_brand_slug" ON "brand" ("Slug");

CREATE TABLE "product" (
  "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "CategoryId" BIGINT NOT NULL,
  "BrandId" BIGINT NOT NULL,
  "Name" varchar(150) NOT NULL,
  "Slug" varchar(200) NOT NULL,
  "DiscountPercent" numeric,
  "Status" varchar(50) NOT NULL DEFAULT 'available',
  "BasePrice" numeric(18,2) NOT NULL,
  "Description" text,
  "Overview" text,
  "Specs" jsonb,
  "TotalSold" INTEGER NOT NULL DEFAULT 0,
  "CreatedAt" timestamp NOT NULL DEFAULT now(),
  "UpdatedAt" timestamp NOT NULL DEFAULT now(),
  "AverageRating" double precision NOT NULL DEFAULT 0,
  "TotalReviews" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("Id")
);
ALTER TABLE "product" ADD CONSTRAINT "fk_product_category" FOREIGN KEY ("CategoryId") REFERENCES "category" ("Id") ON DELETE CASCADE;
ALTER TABLE "product" ADD CONSTRAINT "fk_product_brand" FOREIGN KEY ("BrandId") REFERENCES "brand" ("Id") ON DELETE CASCADE;
CREATE UNIQUE INDEX "idx_product_slug" ON "product" ("Slug");
CREATE INDEX "idx_product_category_brand" ON "product" ("CategoryId", "BrandId");

CREATE TABLE "product_image" (
  "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "ProductId" BIGINT NOT NULL,
  "ImageUrl" text NOT NULL,
  "IsPrimary" boolean NOT NULL DEFAULT false,
  "SortOrder" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("Id")
);
ALTER TABLE "product_image" ADD CONSTRAINT "fk_product_image_product" FOREIGN KEY ("ProductId") REFERENCES "product" ("Id") ON DELETE CASCADE;
CREATE INDEX "idx_product_image_product_id" ON "product_image" ("ProductId");

CREATE TABLE "product_variant" (
  "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "ProductId" BIGINT NOT NULL,
  "Sku" varchar(100) NOT NULL,
  "Price" numeric(12,2) NOT NULL,
  "Stock" INTEGER NOT NULL DEFAULT 0,
  "Status" text NOT NULL DEFAULT 'available',
  "CreatedAt" timestamp NOT NULL DEFAULT now(),
  "VariantSpecsJson" jsonb,
  PRIMARY KEY ("Id")
);
ALTER TABLE "product_variant" ADD CONSTRAINT "fk_product_variant_product" FOREIGN KEY ("ProductId") REFERENCES "product" ("Id") ON DELETE CASCADE;
CREATE UNIQUE INDEX "idx_product_variant_sku" ON "product_variant" ("Sku");
CREATE INDEX "idx_product_variant_product_id" ON "product_variant" ("ProductId");

CREATE TABLE "product_attribute" (
  "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "Name" varchar(100) NOT NULL,
  "InputType" varchar(50) NOT NULL DEFAULT 'select',
  "IsGlobal" boolean NOT NULL DEFAULT false,
  "CreatedAt" timestamp NOT NULL DEFAULT now(),
  "CategoryId" BIGINT,
  PRIMARY KEY ("Id")
);
ALTER TABLE "product_attribute" ADD CONSTRAINT "fk_product_attribute_category" FOREIGN KEY ("CategoryId") REFERENCES "category" ("Id") ON DELETE SET NULL;
CREATE INDEX "idx_product_attribute_category_id" ON "product_attribute" ("CategoryId");

CREATE TABLE "attribute_value" (
  "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "AttributeId" BIGINT NOT NULL,
  "Value" varchar(100) NOT NULL,
  PRIMARY KEY ("Id")
);
ALTER TABLE "attribute_value" ADD CONSTRAINT "fk_attribute_value_attribute" FOREIGN KEY ("AttributeId") REFERENCES "product_attribute" ("Id") ON DELETE CASCADE;
CREATE UNIQUE INDEX "idx_attribute_value_unique" ON "attribute_value" ("AttributeId", "Value");

CREATE TABLE "product_variant_attribute" (
  "VariantId" BIGINT,
  "AttributeId" BIGINT,
  "ValueId" BIGINT NOT NULL,
  PRIMARY KEY ("VariantId", "AttributeId")
);
ALTER TABLE "product_variant_attribute" ADD CONSTRAINT "fk_pva_variant" FOREIGN KEY ("VariantId") REFERENCES "product_variant" ("Id") ON DELETE CASCADE;
ALTER TABLE "product_variant_attribute" ADD CONSTRAINT "fk_pva_attribute" FOREIGN KEY ("AttributeId") REFERENCES "product_attribute" ("Id") ON DELETE CASCADE;
ALTER TABLE "product_variant_attribute" ADD CONSTRAINT "fk_pva_value" FOREIGN KEY ("ValueId") REFERENCES "attribute_value" ("Id") ON DELETE CASCADE;
CREATE INDEX "idx_pva_attribute_value" ON "product_variant_attribute" ("AttributeId", "ValueId");

CREATE TABLE "blog_posts" (
  "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "Title" varchar(200) NOT NULL,
  "Slug" varchar(200) NOT NULL,
  "Summary" varchar(500) NOT NULL,
  "Content" text NOT NULL,
  "FeaturedImageUrl" varchar(500) NOT NULL,
  "AuthorId" BIGINT NOT NULL,
  "Status" varchar(20) NOT NULL,
  "ViewCount" INTEGER NOT NULL DEFAULT 0,
  "PublishedAt" timestamp NOT NULL,
  "CreatedAt" timestamp NOT NULL DEFAULT now(),
  "UpdatedAt" timestamp,
  "ProductIds" text NOT NULL DEFAULT '[]',
  PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX "idx_blog_posts_slug" ON "blog_posts" ("Slug");
CREATE INDEX "idx_blog_posts_status_published_created" ON "blog_posts" ("Status", "PublishedAt", "CreatedAt");

CREATE TABLE "blog_post_tags" (
  "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "BlogPostId" BIGINT NOT NULL,
  "Tag" varchar(50) NOT NULL,
  PRIMARY KEY ("Id")
);
ALTER TABLE "blog_post_tags" ADD CONSTRAINT "fk_blog_post_tags_post" FOREIGN KEY ("BlogPostId") REFERENCES "blog_posts" ("Id") ON DELETE CASCADE;
CREATE INDEX "idx_blog_post_tags_post_tag" ON "blog_post_tags" ("BlogPostId", "Tag");
CREATE INDEX "idx_blog_post_tags_tag" ON "blog_post_tags" ("Tag");

CREATE TABLE "stock_reservation" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "variantId" BIGINT NOT NULL,
  "orderId" BIGINT NOT NULL,
  "quantity" INTEGER NOT NULL,
  "status" varchar(20) NOT NULL,
  "createdAt" timestamp NOT NULL DEFAULT now(),
  "expiresAt" timestamp,
  PRIMARY KEY ("id")
);
