server:
  port: ${PORT:8083}

spring:
  application:
    name: search-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

es:
  host: ${ES_HOST:localhost}
  port: ${ES_PORT:9200}

search:
  reindex:
    cron: "${REINDEX_CRON:0 */15 * * * *}"

product-service:
  url: ${PRODUCT_SERVICE_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
